# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yt_video_id', models.IntegerField()),
                ('yt_video_title', models.CharField(max_length=200)),
                ('yt_video_description', models.CharField(max_length=500)),
            ],
        ),
    ]
