# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_accesscredentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='yt_video_id',
            field=models.CharField(max_length=100),
        ),
    ]
