# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_youtube_yt_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='yt_channel_id',
            field=models.CharField(default='Channel_ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='yt_video_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
