# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_auto_20170523_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscredentials',
            name='access_token',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='accesscredentials',
            name='refresh_token',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
